annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 9.1.1
dependencies:
  - condition: zookeeper.enabled
    name: zookeeper
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Apache Solr is an extremely powerful, open source enterprise search platform built on Apache Lucene. It is highly reliable and flexible, scalable, and designed to add value very quickly after launch.
home: https://github.com/bitnami/charts/tree/main/bitnami/solr
icon: https://bitnami.com/assets/stacks/solr/img/solr-stack-220x234.png
keywords:
  - solr
  - zookeeper
  - apache
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: solr
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/solr
  - https://lucene.apache.org/solr/
version: 7.2.2
