annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.1.0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: JasperReports Server is a stand-alone and embeddable reporting server. It is a central information hub, with reporting and analytics that can be embedded into web and mobile applications.
home: https://github.com/bitnami/charts/tree/main/bitnami/jasperreports
icon: https://bitnami.com/assets/stacks/jasperserver/img/jasperserver-stack-220x234.png
keywords:
  - business intelligence
  - java
  - jasper
  - reporting
  - analytic
  - visualization
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: jasperreports
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jasperreports
  - http://community.jaspersoft.com/project/jasperreports-server
version: 14.4.0
