annotations:
  category: CRM
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.13.2
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: SuiteCRM is a completely open source, enterprise-grade Customer Relationship Management (CRM) application. SuiteCRM is a fork of the popular SugarCRM application.
home: https://github.com/bitnami/charts/tree/main/bitnami/suitecrm
icon: https://bitnami.com/assets/stacks/suitecrm/img/suitecrm-stack-220x234.png
keywords:
  - suitecrm
  - crm
  - http
  - web
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: suitecrm
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/suitecrm
  - https://www.suitecrm.com/
version: 11.3.0
