annotations:
  category: Forum
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.3.10
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: phpBB is a popular bulletin board that features robust messaging capabilities such as flat message structure, subforums, topic split/merge/lock, user groups, full-text search, and attachments.
home: https://github.com/bitnami/charts/tree/main/bitnami/phpbb
icon: https://bitnami.com/assets/stacks/phpbb/img/phpbb-stack-220x234.png
keywords:
  - phpbb
  - forum
  - http
  - php
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: phpbb
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/phpbb
  - https://www.phpbb.com/
version: 12.4.0
