annotations:
  category: CertificateAuthority
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.11.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: cert-manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources.
home: https://github.com/jetstack/cert-manager
icon: https://bitnami.com/assets/stacks/cert-manager/img/cert-manager-stack-220x234.png
keywords:
  - go
  - security
  - tls
  - certificate
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: cert-manager
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/cert-manager
  - https://github.com/bitnami/containers/tree/main/bitnami/cert-manager-webhook
  - https://github.com/bitnami/containers/tree/main/bitnami/cainjector
  - https://github.com/jetstack/cert-manager
version: 0.9.6