annotations:
  category: Analytics
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.13.0
dependencies:
  - condition: kube-state-metrics.enabled
    name: kube-state-metrics
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 3.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Wavefront is a high-performance streaming analytics platform for monitoring and optimizing your environment and applications.
home: https://www.wavefront.com
icon: https://bitnami.com/assets/stacks/wavefront/img/wavefront-stack-220x234.png
keywords:
  - metric
  - monitoring
  - observability
  - alerting
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: wavefront
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/wavefront-kubernetes-collector
  - https://github.com/bitnami/containers/tree/main/bitnami/wavefront-proxy
  - https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
  - https://github.com/wavefrontHQ/wavefront-proxy
version: 4.3.0
