annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.36.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration
home: https://fluxcd.io/
icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
  - deployment
  - gitops
  - cd
  - continuous-delivery
  - helm
  - kustomize
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: flux
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-kustomize-controller
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-helm-controller
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-source-controller
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-notification-controller
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-image-automation-controller
  - https://github.com/bitnami/containers/tree/main/bitnami/fluxcd-image-reflector-controller
  - https://github.com/fluxcd
version: 0.1.2
